---
language: node_js
os:
 - linux
dist: xenial
node_js:
 - node
script:
 - yarn coveralls
cache:
  npm: false
  directories:
    - ./.yarn/cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash 
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
install: yarn
